// tslint:disable:object-literal-sort-keys
const images = {
  animation: require("./animation.json"),
  inviteHeart: require("./invite_heart.png"),
  baselineCasinoBlack18Dp: require("./baselineCasinoBlack18Dp.png"),
  baselineQueueMusicBlack18Dp: require("./baselineQueueMusicBlack18Dp.png"),
  baselineEmojiEventsBlack18Dp: require("./baselineEmojiEventsBlack18Dp.png"),
  correctCD: require("./imageCd.png"),
  wrongCD: require("./imageCd2.png"),
  playCD: require("./imageDefault.png"),
  playButton: require("./button1.png"),
  pauseButton: require("./button.png"),
  buttonHome: require("./buttonHome.png"),
  tooltip: require("./tooltip.png"),
  mirrorball: require("./mirrorball.png"),
  mirrorballLight: require("./mirrorballLight.png"),
  btnKakao: require("./btn_kakao.png"),
  btnFacebook: require("./btn_facebook.png"),
  btnGoogle: require("./btn_google.png"),
  addEmpty: require("./group3Copy.png"),
  closeIcon: require("./group.png"),
  mainMirrorBall: require("./group12.png"),
  btnRankIcon: require("./group14.png"),
  btnCDIcon: require("./btn_cd.png"),
  combinedShape: require("./combinedShape.png"),
  splash: require("./splash.png"),
  podium: require("./podium.png"),
  bgCorrectMirrorballLight: require("./bg_correct_mirrorballLight.png"),
  pencil: require("./pencil.png"),
  bgMain: require("./bg_main.png"),
  note: require("./note.png"),
  miniHeart: require("./group3Copy2.png")
};
export default images;
