/* eslint-disable @typescript-eslint/camelcase */
import _ from "lodash";

export const mockTracks = _.times(10, () => ({
  id: 310756839,
  kind: "track",
  created_at: "2017/03/05 01:29:45 +0000",
  last_modified: "2017/03/05 01:29:46 +0000",
  permalink: "c-4",
  permalink_url: "https://soundcloud.com/mic1gvtyqkzk/c-4",
  title: "금잔디c - 오라버니",
  duration: 190659,
  sharing: "public",
  waveform_url: "https://wave.sndcdn.com/lFHwx86wEciB_m.png",
  stream_url: "https://api.soundcloud.com/tracks/310756839/stream",
  uri: "https://api.soundcloud.com/tracks/310756839",
  user_id: 289053373,
  artwork_url:
    "https://i1.sndcdn.com/artworks-000210834377-g9ra6q-large.jpg",
  comment_count: 1,
  commentable: true,
  description: "플레이스토어에서  `뮤직탑` 검색하세요",
  download_count: 0,
  downloadable: false,
  embeddable_by: "all",
  favoritings_count: 0,
  genre: "",
  isrc: null,
  label_id: null,
  label_name: null,
  license: "all-rights-reserved",
  original_content_size: 7796512,
  original_format: "mp3",
  playback_count: 0,
  purchase_title: null,
  purchase_url: null,
  release: "",
  release_day: null,
  release_month: null,
  release_year: null,
  reposts_count: 8,
  state: "finished",
  streamable: true,
  tag_list: '"전통음악 > 트로트"',
  track_type: null,
  user: {
    avatar_url:
      "https://i1.sndcdn.com/avatars-000299828543-hd8q8e-large.jpg",
    id: 289053373,
    kind: "user",
    permalink_url: "http://soundcloud.com/mic1gvtyqkzk",
    uri: "https://api.soundcloud.com/users/289053373",
    username: "뮤직탑(MusicTOP)2",
    permalink: "mic1gvtyqkzk",
    last_modified: "2017/03/05 01:26:55 +0000"
  },
  likes_count: 59,
  bpm: null,
  key_signature: "",
  user_favorite: false,
  user_playback_count: null,
  video_url: null,
  download_url: null
}));
