name: Android Release
on:
  push:
    branches:
      - "master*"

jobs:
  ipa:
    name: Generate APK
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - name: Fastlane step
        uses: maierj/fastlane-action@v1.2.0
        with:
          lane: "android ci"
        env:
          APP_DISPLAY_NAME: "RNApp"
          OUTPUT_NAME: "RNApp"
          OUTPUT_SUFFIX: ""
          PRODUCT_BUNDLE_IDENTIFIER: "kr.rnapp.apptest"
          XCODE_TEAM_ID: "787Q6972XA"
          XCODE_SCHEME: "RNApp"
          XCODE_PROJECT_NAME: "RNApp"
          XCODE_CODE_SIGN_ID: "Apple Distribution: Junhui Kim (787Q6972XA)"
          XCODE_PROVISIONING_PROFILE_NAME: "191f3fe5-d9ee-4e6b-bc6e-e7fe2bfe5b42.kr.rnapp.apptest"
          XCODE_PROVISIONING_PROFILE_UUID: "191f3fe5-d9ee-4e6b-bc6e-e7fe2bfe5b42"
          FIREBASE_TOKEN: "1//0eJGW5rUC4NBRCgYIARAAGA4SNwF-L9IraQk7cq7VUh660mt0OCTG_JWyQfMzkwVxm3ngcWrRQRYRHvEZTx4hRHDdxhZd1Eq3FGw"
